name: Mise à jour Météo

on:
  schedule:
    # S'exécute à 12h15 UTC tous les jours (soit 8h15 EDT)
    # EC publie ses relevés à 10h UTC. Nous ajoutons 2 heures de délai pour que MeteoStat puisse récupérer les données mondiales et mettre à jour ses bases de données.
    # En plus, nous évitons l'heure juste afin d'éviter l'engorgement du serveur par des millions de demandes automatiques mondiales aux heures piles. 
    - cron: '15 12 * * *'
  workflow_dispatch: # Permet de tester manuellement avec un bouton

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5
      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.10' # Ou votre version actuelle de Python
      - name: Installation des librairies
        run: pip install -r requirements.txt
      - name: Exécution du script
        run: python meteo.py
      - name: Sauvegarde du résultat
        run: |
          git config --global user.email "action@github.com"
          git config --global user.name "GitHub Action"
          git add resultat.txt
          git commit -m "Mise à jour quotidienne de la pluie" || exit 0
          git push
